### ISSUE TITLE
[suggestion] abuse prevention

### ISSUE THREAD

**Issue by ruyanve** [Team-Fruit/SignPicture#4]
I really like the idea of this mod, but fear some players will abuse the mod with profane pictures or other kinds of grief.
Maybe we could come up with a way to allow the mod to be fun, but restrict possible abusive use?
Blocking certain words from image files would be a easy way to go at the problem, but may also be as easily circumvented.
A permission system would be a good idea but not a guarantee to never see dick pics. A way to approve the selected images by an admin/mod would solve that, but involves work and people like me still looking at dick pics.
And I'm guessing since this is a client side mod, any form of server interaction is out of the picture to begin with?
Otherwise I'd love to see a local file option, like giving players a selection of pictures they can choose from. Maybe even a per point system? Like a player needs to earn/find points to place images... 

Anyway, I'll be handing this out to players soon and will report back with what they came up with and maybe more insight in the subject.

**Comment by Kamesuta** [comment]
I also was thinking the same thing, but in order to achieve is likely to take a long time. Create a Spigot plug-ins, to analyze the grammar of sign, we would like to be able to limit the white list, black list, offset, size and the like.
However, I am, because you want to give priority to the development of new functions of the Mod, might be postponed. If, if you could have a knowledge of the plug-in, and we'd appreciate it if you could cooperate in such PullRequest.
[SignPictureManager(WIP)](https://github.com/Kamesuta/SignPictureManager)

---
私も同じようなことを考えていましたが、実現するには時間がかかりそうです。Spigotプラグインを作成し、看板の文法を解析し、ホワイトリスト、ブラックリスト、オフセット、サイズなどを制限できるようにしたいと考えております。
しかし、私は、Modの新機能の開発を優先したいため、後回しになるかもしれません。もし、あなたがプラグインについての知識をお持ちでしたら、PullRequestなどで協力していただけると助かります。
[SignPictureManager(WIP)](https://github.com/Kamesuta/SignPictureManager)

**Comment by ruyanve** [comment]
Sadly I lack the knowledge and time to write such a plugin myself. I also think you should stay away from spigot and stick to forge via sponge if you want to have server interaction (if I understood you correctly).

Permission nodes would be a great thing to have tho... :-)

**Comment by sjcl** [comment]
Since Spigot plugin and the dialogue of the Forge mod is possible, there is no concern. 
In addition, if the server is a Forge environment, by introducing a SignPicture Mod to the server, we believe that trying to implement so as to obtain a similar function.   
Well, in the case of Forge it can not be used with permission node, but ... :<
***
Spigot pluginとForge modの対話は可能なので、懸念はありません。 
また、サーバーがForge環境の場合は、SignPicture Modをサーバーに導入する事によって、同様の機能を得られるように実装しようと考えています。  
まあ、Forgeの場合はパーミッションノードは使用できませんが・・・ :<

**Comment by ruyanve** [comment]
We're waiting for this to be accepted: https://github.com/MinecraftForge/MinecraftForge/pull/3155

**Comment by sjcl** [comment]
I did not know it, but it is very interesting. We will wait to accept in the hope. 
However, it is likely to be implemented after the Forge of Minecraft1.10.x. 
If there is high need for permission node, after the spigot plugin has been completed, also consider porting to sponge plugins.
***
私はそれを知りませんでしたが、とても興味深いです。期待して受け入れを待とうと思います。 
しかし、それはMinecraft1.10.xのForge以降に実装されると思われます。 
パーミッションノードの必要性が高い場合には、spigot プラグインが完成した後、sponge プラグインへの移植も検討します。

**Comment by ruyanve** [comment]
Well, it's hard to foresee how Forge development will pan out... I have been around long enough to just ride the wave and see what comes out, there's no arguing with Lex (and maybe that's a good thing!). But my fingers are crossed for this and Microblocks to be accepted before 1.12 happens :-P

If Sponge manages to improve performance while in a Forge server environment I hope it'll prevail and Spigot will slowly fade away. That has always been a great divider in the Minecraft Community.

Also I wanted to tell you, that I am happy to see Japanese Modders come around, I don't remember ever seeing any major Japanese mod before that was useable by non-japanese speaking people. I flew around a Japanese Forum once and saw all kinds of interesting mods, that I couldnt use because no other languages were supported. Your work is greatly appreciated!
有難う 御座います

**Comment by sjcl** [comment]
I, I have accidentally management of the label ...

**Comment by ruyanve** [comment]
Well, I guess this can be closed anyway :-)

**Comment by sjcl** [comment]
We would like also developed proactively in Sponge.
My English is poor, but I would like to continue the support in languages other than Japanese now.
Thank you for your suggestion :-)

**Comment by ruyanve** [comment]
Well, if you need someone to help you with English translations, just poke me. I'll gladly translate anything to German as well.
